[tool.poetry]
name = "findmy-py"
version = "0.1.0"
description = "Everything you need to query Apple's Find My network!"
authors = ["Mike Almeloo <git@mikealmel.ooo>"]
readme = "README.md"
packages = [{ include = "findmy" }]

[tool.poetry.dependencies]
python = "^3.10"
srp = "^1.0.20"
cryptography = "^41.0.7"
beautifulsoup4 = "^4.12.2"
aiohttp = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
