name: Pre-commit

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --with dev,test
    
    - uses: pre-commit/action@v3.0.1
    
    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
