name: Pre-commit

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: './.github/actions/setup-project'
      with:
        dependency-groups: 'dev,test'
    
    - uses: pre-commit/action@v3.0.1
    
    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
