name: Upload Python Package


on:
  workflow_dispatch:
  push:
    tags:        
      - 'v[0-9]\.[0-9]+\.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install
      
    - name: Build package
      run: poetry build
    
    - name: Publish package
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry publish
